services:
  api:
    build: ./api
    expose:
      - "8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - nexus-arcana

networks:
  nexus-arcana:
    external: true
    name: nexus-arcana_default
